#!/bin/sh
#
#

case "$1" in
  start)
 	echo "Starting insmod..."
	insmod /lib/modules/nx_vpu.ko
	insmod /lib/modules/vr.ko
	;;
  stop)
	echo -n "Stopping insmod..."
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

