#!/bin/sh
#
#

case "$1" in
  start)
 	echo "Starting performance..."
	echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	;;
  stop)
	echo -n "Stopping performance..."
	echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

